name: Build and release

on:
  push

permissions:
  contents: write  # Required by action-gh-release

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: gradle/actions/setup-gradle@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - run: ./gradlew clean build

      - uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: build/test-results/test/*.xml
          fail_on_failure: true
          include_passed: false
          detailed_summary: true

      - uses: anothrNick/github-tag-action@v1
        if: github.ref == 'refs/heads/main' && github.ref_type != 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            build/distributions/Route53a4k.tar
            build/distributions/Route53a4k.zip
            build/libs/Route53a4k.jar